name: Unit tests

on:
  # push:
  #   branches: [ main ]
  #   paths-ignore:
  #         - '.github/workflows/feature.*'
  #         - '.github/workflows/pull-request.*'

  workflow_dispatch:

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Configure
        shell: bash
        run: npm install

      - name: Unit test
        shell: bash
        run: npm test