name: Unit tests

on:
  # push:
  #   branches: [ main ]
  #   paths-ignore:
  #         - '.github/workflows/feature.*'
  #         - '.github/workflows/pull-request.*'

  workflow_dispatch:

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    container: node:lts

    defaults:
      run:
        working-directory: ./service

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: List files
        shell: bash
        run: ls -la

      - name: Check node
        shell: bash
        run: node -v

      - name: Check npm
        shell: bash
        run: npm -v

      - name: Install dependencies
        shell: bash
        run: npm install

      - name: Unit tests
        shell: bash
        run: npm test